name: Minikube Cluster Setup
on:
 push:
   branches:
     - main
jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Minikube
        uses: appleboy/setup-minikube@v1
        with:
          kubernetes_version: v1.21.2
      - name: Start Minikube
        run: minikube start
