name: Minikube Cluster Setup
on:
 push:
   branches:
     - main

jobs:
  setup-minikube:
    runs-on: self-hosted
    steps:
     - name: Set up Minikube
       run: |
         minikube start --driver=hyperv
         minikube addons enable ingress
     - name: Verify Minikube cluster
       run: |
         kubectl get nodes
         kubectl get pods --all-namespaces
     - name: Stop Minikube
       run: minikube stop
